using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

[InitializeOnLoad]
public static class GuardrailCropper
{
    private const string SourcePrefab = "Assets/Models/Metal Guardrail/Metal Guardrail.prefab";
    private const string OutputDir = "Assets/Models/Metal Guardrail/Cropped";
    private const string OutputMesh = OutputDir + "/Metal Guardrail_2Part.asset";
    private const string OutputPrefab = OutputDir + "/Metal Guardrail_2Part.prefab";
    private const string AutoRunKey = "GuardrailCropper.AutoGenerated2Part";
    private const float KeepStartRatio = 0.035f;
    private const float KeepEndRatio = 0.73f;

    static GuardrailCropper()
    {
        EditorApplication.delayCall += () =>
        {
            if (SessionState.GetBool(AutoRunKey, false)) return;
            if (!AssetDatabase.LoadAssetAtPath<GameObject>(SourcePrefab)) return;
            if (AssetDatabase.LoadAssetAtPath<GameObject>(OutputPrefab)) return;

            SessionState.SetBool(AutoRunKey, true);
            Generate();
        };
    }

    [MenuItem("Tools/Generate Cropped Guardrail")]
    public static void Generate()
    {
        Directory.CreateDirectory(OutputDir);
        AssetDatabase.DeleteAsset(OutputMesh);
        AssetDatabase.DeleteAsset(OutputPrefab);

        GameObject root = PrefabUtility.LoadPrefabContents(SourcePrefab);
        try
        {
            MeshFilter[] filters = root.GetComponentsInChildren<MeshFilter>(true);
            if (filters.Length == 0)
            {
                Debug.LogError("[GuardrailCropper] No MeshFilter found.");
                return;
            }

            Bounds rootBounds = CalculateRootLocalBounds(root.transform, filters);
            float keepMinX = Mathf.Lerp(rootBounds.min.x, rootBounds.max.x, KeepStartRatio);
            float keepMaxX = Mathf.Lerp(rootBounds.min.x, rootBounds.max.x, KeepEndRatio);

            var generatedMeshes = new List<Object>();
            foreach (MeshFilter filter in filters)
            {
                Mesh cropped = CropMeshByRootX(root.transform, filter, keepMinX, keepMaxX);
                if (cropped == null)
                {
                    filter.gameObject.SetActive(false);
                    continue;
                }

                cropped.name = filter.sharedMesh.name + "_2Part";
                if (generatedMeshes.Count == 0)
                    AssetDatabase.CreateAsset(cropped, OutputMesh);
                else
                    AssetDatabase.AddObjectToAsset(cropped, OutputMesh);
                generatedMeshes.Add(cropped);
                filter.sharedMesh = cropped;
            }

            if (generatedMeshes.Count == 0)
            {
                Debug.LogError("[GuardrailCropper] Crop produced no meshes.");
                return;
            }

            PrefabUtility.SaveAsPrefabAsset(root, OutputPrefab);
            AssetDatabase.SaveAssets();
            AssetDatabase.ImportAsset(OutputPrefab);

            Debug.Log($"[GuardrailCropper] Generated {OutputPrefab} with keepX={keepMinX}..{keepMaxX}, rootBounds={rootBounds}.");
        }
        finally
        {
            PrefabUtility.UnloadPrefabContents(root);
        }
    }

    private static Bounds CalculateRootLocalBounds(Transform root, MeshFilter[] filters)
    {
        bool hasBounds = false;
        Bounds bounds = new Bounds();

        foreach (MeshFilter filter in filters)
        {
            Mesh mesh = filter.sharedMesh;
            if (mesh == null) continue;

            Vector3[] vertices = mesh.vertices;
            foreach (Vector3 vertex in vertices)
            {
                Vector3 rootPoint = root.InverseTransformPoint(filter.transform.TransformPoint(vertex));
                if (!hasBounds)
                {
                    bounds = new Bounds(rootPoint, Vector3.zero);
                    hasBounds = true;
                }
                else
                {
                    bounds.Encapsulate(rootPoint);
                }
            }
        }

        return bounds;
    }

    private static Mesh CropMeshByRootX(Transform root, MeshFilter filter, float keepMinX, float keepMaxX)
    {
        Mesh source = filter.sharedMesh;
        if (source == null) return null;

        Vector3[] sourceVertices = source.vertices;
        Vector3[] sourceNormals = source.normals;
        Vector4[] sourceTangents = source.tangents;
        Vector2[] sourceUv = source.uv;
        Color[] sourceColors = source.colors;

        var vertices = new List<Vector3>();
        var normals = new List<Vector3>();
        var tangents = new List<Vector4>();
        var uv = new List<Vector2>();
        var colors = new List<Color>();
        var indexMap = new Dictionary<int, int>();
        var subTriangles = new List<int>[source.subMeshCount];

        for (int sub = 0; sub < source.subMeshCount; sub++)
        {
            int[] tris = source.GetTriangles(sub);
            var kept = new List<int>();

            for (int i = 0; i < tris.Length; i += 3)
            {
                int a = tris[i];
                int b = tris[i + 1];
                int c = tris[i + 2];

                if (!IsKept(root, filter.transform, sourceVertices[a], keepMinX, keepMaxX)) continue;
                if (!IsKept(root, filter.transform, sourceVertices[b], keepMinX, keepMaxX)) continue;
                if (!IsKept(root, filter.transform, sourceVertices[c], keepMinX, keepMaxX)) continue;

                kept.Add(MapIndex(a));
                kept.Add(MapIndex(b));
                kept.Add(MapIndex(c));
            }

            subTriangles[sub] = kept;
        }

        if (vertices.Count == 0) return null;

        var mesh = new Mesh();
        mesh.indexFormat = vertices.Count > 65535
            ? UnityEngine.Rendering.IndexFormat.UInt32
            : UnityEngine.Rendering.IndexFormat.UInt16;
        mesh.SetVertices(vertices);
        if (normals.Count == vertices.Count) mesh.SetNormals(normals);
        if (tangents.Count == vertices.Count) mesh.SetTangents(tangents);
        if (uv.Count == vertices.Count) mesh.SetUVs(0, uv);
        if (colors.Count == vertices.Count) mesh.SetColors(colors);
        mesh.subMeshCount = source.subMeshCount;
        for (int sub = 0; sub < subTriangles.Length; sub++)
            mesh.SetTriangles(subTriangles[sub], sub);
        mesh.RecalculateBounds();
        if (normals.Count != vertices.Count) mesh.RecalculateNormals();
        return mesh;

        int MapIndex(int sourceIndex)
        {
            if (indexMap.TryGetValue(sourceIndex, out int mapped)) return mapped;

            mapped = vertices.Count;
            indexMap[sourceIndex] = mapped;
            vertices.Add(sourceVertices[sourceIndex]);
            if (sourceNormals != null && sourceNormals.Length == sourceVertices.Length) normals.Add(sourceNormals[sourceIndex]);
            if (sourceTangents != null && sourceTangents.Length == sourceVertices.Length) tangents.Add(sourceTangents[sourceIndex]);
            if (sourceUv != null && sourceUv.Length == sourceVertices.Length) uv.Add(sourceUv[sourceIndex]);
            if (sourceColors != null && sourceColors.Length == sourceVertices.Length) colors.Add(sourceColors[sourceIndex]);
            return mapped;
        }
    }

    private static bool IsKept(Transform root, Transform meshTransform, Vector3 meshVertex, float keepMinX, float keepMaxX)
    {
        Vector3 rootPoint = root.InverseTransformPoint(meshTransform.TransformPoint(meshVertex));
        return rootPoint.x >= keepMinX && rootPoint.x <= keepMaxX;
    }
}
